spring:
  config:
    activate:
      on-profile: test-auth
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: emptyValueForTest
            clientSecret: emptyValueForTest
            scope: profile,email
  mail:
    host: smtp.gmail.com
    port: 587
    username: ddokddak.dev
    password: lzvsedqxmwkgrxoq
    properties:
      mail:
        smtp:
          ssl:
            protocols: TLSv1.2
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          write timeout: 5000
    auth-code-expiration-millis: 300000  # 5 * 60 * 1000 == 5분

# 토큰 관련 secret Key 및 RedirectUri 설정
auth:
  token:
    tokenSecret: emptyValueForTest
    tokenExpirationMS: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000