# default
spring:
  profiles:
    active: local # dev-local
    group:
      local: local, common, auth
      test: test, common, test-auth
      dev:  common, dev, auth, prod-db
      prod: common, prod, auth, prod-db
      dev-local: local, common, auth, prod-db

---
# common 환경
spring:
  config:
    activate:
      on-profile: common
  jackson:
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false # 타임존 UTC로 자동 변경 해제
  datasource:
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true # 배치 인서트 쿼리 활용 설정
  thymeleaf: ## thymeleaf default settings
    prefix: classpath:/mail-templates/ # 이메일 템플릿이 위치할 경로. classpath:를 통해 src/main/resources/ 밑으로 설정되었다.
    suffix: .html # 템플릿 파일의 확장자
    mode: HTML
    encoding: UTF-8
    check-template-location: true
  ## thymeleaf custom settings
    cache: false

# 벌크 인서트 제한
jdbc:
  batch:
    size: 10000

# cors 설정
cors:
  allowedOriginPatterns: 'http://localhost:3000'
  allowedMethods: GET,POST,PUT,PATCH,DELETE,OPTIONS
  allowedHeaders: '*'
  maxAgeSec: 3600
server:
  port: 8080
  forward-headers-strategy: framework

# 앱 속성
app:
  baseUrl: 'http://localhost:3000'
  version: v1.0.0

---
# test 환경
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE  # db 주소 고정
  sql:
    init:
      data-locations: classpath:data.sql # 시작할때 실행시킬 script
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true # hibernate가 초기화되기 전 data.sql 실행하는 것을 방지
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    root: DEBUG
    org:
      springframework:
        security: DEBUG

---
# local 환경
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # jdbc 로그 확인 위해 옵션 수정
    url: jdbc:mysql://localhost:3306/dodone?characterEncoding=UTF-8&profileSQL=true&c=Slf4JLogger&maxQuerySizeToLog=999999
    username: root
    password: 1234
  jpa:
    defer-datasource-initialization: true # hibernate가 초기화되기 전 data.sql 실행하는 것을 방지
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create # 데이터를 쌓아두려면, 해당 속성을 update로 지정
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  devtools:
    livereload:
      enabled: true
logging:
  level:
    root: DEBUG
    org:
      springframework:
        security: DEBUG

---
# prod 환경
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: none
logging:
  level:
#    root: DEBUG
    org:
      springframework:
        security: DEBUG
# cors 설정
cors:
  allowedOriginPatterns: 'https://dodonenow.com'
  allowedMethods: GET,POST,PUT,PATCH,DELETE,OPTIONS
  allowedHeaders: '*'
  maxAgeSec: 3600

app:
  baseUrl: 'https://dodonenow.com'

---
# dev 환경
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
logging:
  level:
    #    root: DEBUG
    org:
      springframework:
        security: DEBUG

# cors 설정
cors:
  allowedOriginPatterns: '*'
#    - 'http://localhost:3000'
#    - 'https://dodonenow.com'
  allowedMethods: GET,POST,PUT,PATCH,DELETE,OPTIONS
  allowedHeaders: '*'
  maxAgeSec: 3600
app:
  baseUrl: 'http://localhost:3000'

---
# dev-local 환경
spring:
  config:
    activate:
      on-profile: dev-local
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
      data-locations: classpath:data.sql