spring:
  config:
    activate:
      on-profile: test-auth
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: emptyValueForTest
            clientSecret: emptyValueForTest
            scope: profile,email
          naver:
            clientId: emptyValueForTest
            clientSecret: emptyValueForTest
            authorizationGrantType: authorization_code
            #clientName: Naver
            redirectUri: "{baseUrl}/api/login/oauth2/code/naver"
            scope:
              - email
              - nickname
          kakao:
            clientId: emptyValueForTest
            clientSecret: emptyValueForTest
            clientAuthenticationMethod: client_secret_post
            authorizationGrantType: authorization_code
            redirectUri: "{baseUrl}/api/login/oauth2/code/kakao"
            scope:
              - profile_nickname
              - account_email
        provider:
          google:
            authorizationUri: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&prompt=consent
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize #?prompt=login
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response
  mail:
    host: smtp.gmail.com
    port: 587
    username: emptyValueForTest
    password: emptyValueForTest
    properties:
      mail:
        smtp:
          mock: true
          ssl:
            protocols: TLSv1.2
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          write timeout: 5000
    auth-code-expiration-millis: 300000  # 5 * 60 * 1000 == 5분

# 토큰 관련 secret Key 및 RedirectUri 설정
auth:
  token:
    tokenSecret: emptyValueForTestemptyValueForTestemptyValueForTestemptyValueForTest
    tokenExpirationMS: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000